#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'robot-ws-bridge','console_scripts','robot_ws_bridge'
__requires__ = 'robot-ws-bridge'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('robot-ws-bridge', 'console_scripts', 'robot_ws_bridge')()
    )
